#!/bin/sh

echo -n "select network(main_skip,main_skipi2,main_noskip,main_noskip2):"
read network
echo -n "insert GPU number:"
read gpu
echo -n "insert GPU factor:"
read gpu_factor
echo -n "insert dataset:"
read datasetname

if [ -z "$gpu" ]||[-z "$gpu_factor"]||[-z "$datasetname"]
then
    echo "Dont forget insert GPU number, GPU factor and datasetname  \n"
exit
else
CUDA_VISIBLE_DEVICES=$gpu python $network'.py' --gpu $gpu_factor --dataset $datasetname
fi

